# 配置文件模板
service:
  name: basicuser                 #basic-user服务
  image: 192.168.1.102:5000/mss/basicuser
  port: 8080
  env:
    REGISTRY_IP: eureka-server
    REGISTRY_PORT: 8000
    MYSQLHOST: basic-user-mysql
experiment:
  name: 实验1
  node: k8s-master                    #pod 的运行节点 默认主节点了
  namespace: default                  # 命名空间
  resource:                           # pod 的资源限制
    cpu:
      start: 200
      end: 1001
      step: 50
  user:  # 模拟的用户数量
    start: 10
    end: 1000
    step: 10
    time: 60 # 用户请求时间，单位为s
  data: ./requestBody/basicuser  # 请求信息文件
  result: ./result/basicuser # 实验结果存放路径
  performance-data: ./performancedata/basicuser
debug: false  # 开启则不加载及执行 pod 部署操作