apiVersion: v1
kind: Pod
metadata:
  name: NAME
spec:
  containers:
    - name: NAME
      image: IMAGE
      imagePullPolicy: Always
      resources:
        limits:
          memory: "200Mi"
          cpu: 1000m
        requests:
          memory: 200Mi
          cpu: 10m
      env:
        - name: REGISTRY_IP
          value: IP
        - name: REGISTRY_PORT
          value: PORT
        - name: MYSQLHOST
          value: 'NONE'
  nodeSelector:
    node: NODE
