apiVersion: v1
kind: Pod
metadata:
  name: NAME
spec:
  containers:
  - name: NAME
    image: IMAGE
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "200Mi"
        cpu: 1000m
      requests:
        memory: "100Mi"
        cpu: 500m
    env:
      - name: REGISTRY_IP
        value: IP
      - name: REGISTRY_PORT
        value: PORT
  nodeSelector:
    node: NODE
